[project]
authors = ["Johannes Hermann <linuxrider@web.de>"]
channels = ["conda-forge"]
name = "svgdigitizer-web"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
nodejs = ">=24.9.0,<24.10"
